### ISSUE TITLE
"Add a block" widget

### ISSUE THREAD

**Issue by DHusband81** [moodleuulm/moodle-theme_boost_campus_child#3]
Version 3.8.2+
The addablockposition feature is not applied in boost_campus_child. The code from boost config is not applied in boost_campus_child.

Regards
David

**Comment by abias** [comment]
Hey @DHusband81 ,

thanks for raising this issue and sorry for the late reply on our side.

@Kathrin84 solved this issue in https://github.com/moodleuulm/moodle-theme_boost_campus_child/commit/9d270d6a6b3c271918dcb9748b1c414e833d76aa and pushed a new version for 3.8 to the Moodle plugin repo, just before releasing the 3.9 version of the plugin.

Cheers,
Alex
